require 'jekyll'
require 'mini_magick'
require 'jekyll-image-resizer/version'
require 'jekyll-image-resizer/command'
require 'jekyll-image-resizer/resizer'
require 'jekyll-image-resizer/water_mark'
require 'jekyll-image-resizer/processor'
require 'jekyll-image-resizer/thumbnail'
